[package]
name = "PoC_tui_components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.1"

[dev-dependencies]
rusty-hook = "0.11.2"
